export const mockMovies = {
  page: 1,
  results: [
    {
      backdrop_path: '/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg',
      id: 426063,
      title: 'Nosferatu',
      original_title: 'Nosferatu',
      overview:
        'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
      poster_path: '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 14, 27],
      popularity: 693.489,
      release_date: '2024-12-25',
      video: false,
      vote_average: 6.7,
      vote_count: 1206,
    },
    {
      backdrop_path: '/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg',
      id: 993710,
      title: 'Back in Action',
      original_title: 'Back in Action',
      overview:
        'Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.',
      poster_path: '/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35],
      popularity: 1161.824,
      release_date: '2025-01-15',
      video: false,
      vote_average: 6.682,
      vote_count: 355,
    },
    {
      backdrop_path: '/b85bJfrTOSJ7M5Ox0yp4lxIxdG1.jpg',
      id: 939243,
      title: 'Sonic the Hedgehog 3',
      original_title: 'Sonic the Hedgehog 3',
      overview:
        'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
      poster_path: '/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 35, 10751],
      popularity: 3560.42,
      release_date: '2024-12-19',
      video: false,
      vote_average: 7.6,
      vote_count: 726,
    },
    {
      backdrop_path: '/rDa3SfEijeRNCWtHQZCwfbGxYvR.jpg',
      id: 539972,
      title: 'Kraven the Hunter',
      original_title: 'Kraven the Hunter',
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      poster_path: '/i47IUSsN126K11JUzqQIOi1Mg1M.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 12, 14, 53],
      popularity: 4706.901,
      release_date: '2024-12-11',
      video: false,
      vote_average: 6.56,
      vote_count: 704,
    },
    {
      backdrop_path: '/haX32ZQxOgDWcJO5sTiTUEE1Ulr.jpg',
      id: 1388694,
      title: 'The Calendar Killer',
      original_title: 'Sebastian Fitzeks Der Heimweg',
      overview: '',
      poster_path: '/bnciRmZZSdyqp7HcrAwNG0mObaP.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'de',
      genre_ids: [80, 53],
      popularity: 247.037,
      release_date: '2025-01-15',
      video: false,
      vote_average: 6.4,
      vote_count: 78,
    },
    {
      backdrop_path: '/uKb22E0nlzr914bA9KyA5CVCOlV.jpg',
      id: 402431,
      title: 'Wicked',
      original_title: 'Wicked',
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: '/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10749, 14],
      popularity: 1060.159,
      release_date: '2024-11-20',
      video: false,
      vote_average: 7.0,
      vote_count: 1402,
    },
    {
      backdrop_path: '/wwARk7hRIfHfh2n2ubN6N7lvTne.jpg',
      id: 710295,
      title: 'Wolf Man',
      original_title: 'Wolf Man',
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      poster_path: '/tUtuMtC6oaRXr4x2B5Xi6ABdMCv.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27, 53],
      popularity: 321.207,
      release_date: '2025-01-15',
      video: false,
      vote_average: 6.8,
      vote_count: 69,
    },
    {
      backdrop_path: '/m8iL42J8CuXh745BaQBa6b1mNrP.jpg',
      id: 1101448,
      title: 'Unstoppable',
      original_title: 'Unstoppable',
      overview:
        'Unstoppable is the inspiring true story of Anthony Robles who was born with one leg but whose unbreakable resolve empowered him to defy the odds and pursue his dreams. With the unwavering love and support of his devoted mother and the encouragement of his coaches, Anthony fights through adversity to earn a spot on the Arizona State Wrestling team on his quest to become an NCAA Champion.',
      poster_path: '/xanYKxuFkDPrMngvm1NSHVGOEjS.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 36],
      popularity: 111.895,
      release_date: '2024-12-06',
      video: false,
      vote_average: 3.8,
      vote_count: 58,
    },
    {
      backdrop_path: '/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg',
      id: 1249289,
      title: 'Alarum',
      original_title: 'Alarum',
      overview:
        'Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.',
      poster_path: '/v313aUGmMNj6yNveaiQXysBmjVS.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 80, 53],
      popularity: 322.549,
      release_date: '2025-01-16',
      video: false,
      vote_average: 5.6,
      vote_count: 26,
    },
    {
      backdrop_path: '/bFPqSvR2EmWQ9AlzWkC801XpoAZ.jpg',
      id: 933260,
      title: 'The Substance',
      original_title: 'The Substance',
      overview:
        'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
      poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27, 878],
      popularity: 835.736,
      release_date: '2024-09-07',
      video: false,
      vote_average: 7.129,
      vote_count: 3354,
    },
    {
      backdrop_path: '/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg',
      id: 1013850,
      title: 'A Real Pain',
      original_title: 'A Real Pain',
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      poster_path: '/yaTFjMNh8D78dDHrglivOTv5YOx.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [35, 18],
      popularity: 272.615,
      release_date: '2024-11-01',
      video: false,
      vote_average: 6.8,
      vote_count: 239,
    },
    {
      backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
      id: 823219,
      title: 'Flow',
      original_title: 'Straume',
      overview:
        'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
      poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'lv',
      genre_ids: [16, 14, 12],
      popularity: 528.119,
      release_date: '2024-08-29',
      video: false,
      vote_average: 8.4,
      vote_count: 840,
    },
    {
      backdrop_path: '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
      id: 558449,
      title: 'Gladiator II',
      original_title: 'Gladiator II',
      overview:
        'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.',
      poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 12, 18],
      popularity: 1487.663,
      release_date: '2024-11-05',
      video: false,
      vote_average: 6.753,
      vote_count: 2436,
    },
    {
      backdrop_path: '/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg',
      id: 1064213,
      title: 'Anora',
      original_title: 'Anora',
      overview:
        'A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.',
      poster_path: '/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10749, 35, 18],
      popularity: 360.43,
      release_date: '2024-10-14',
      video: false,
      vote_average: 7.0,
      vote_count: 769,
    },
    {
      backdrop_path: '/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg',
      id: 762509,
      title: 'Mufasa: The Lion King',
      original_title: 'Mufasa: The Lion King',
      overview:
        'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
      poster_path: '/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [12, 10751, 16],
      popularity: 2536.153,
      release_date: '2024-12-18',
      video: false,
      vote_average: 7.434,
      vote_count: 808,
    },
    {
      backdrop_path: '/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg',
      id: 912649,
      title: 'Venom: The Last Dance',
      original_title: 'Venom: The Last Dance',
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: '/aosm8NMQ3UyoBVpSxyimorCQykC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 878, 12],
      popularity: 1529.072,
      release_date: '2024-10-22',
      video: false,
      vote_average: 6.8,
      vote_count: 2492,
    },
    {
      backdrop_path: '/2V3kokgBD0owybmZMzz8TsYlTZ1.jpg',
      id: 1059128,
      title: 'Queer',
      original_title: 'Queer',
      overview:
        '1950. William Lee, an American expat in Mexico City, spends his days almost entirely alone, except for a few contacts with other members of the small American community. His encounter with Eugene Allerton, an expat former soldier, new to the city, shows him, for the first time, that it might be finally possible to establish an intimate connection with somebody.',
      poster_path: '/xe4b2TMciLKA1C0JlhWxb4ENLln.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 10749],
      popularity: 282.929,
      release_date: '2024-11-27',
      video: false,
      vote_average: 7.2,
      vote_count: 112,
    },
    {
      backdrop_path: '/zGT6zikFjC5wRROXbPIipKahZn8.jpg',
      id: 850439,
      title: 'The Damned',
      original_title: 'The Damned',
      overview:
        'A 19th-century widow is tasked with making an impossible choice when, during an especially cruel winter, a ship sinks off the coast of her impoverished Icelandic fishing village. Any attempt to rescue survivors risks further depleting the starving villagers’ supplies.',
      poster_path: '/fAXDQny8kEquc1BImiQHhYMGSsW.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 27, 9648],
      popularity: 23.53,
      release_date: '2025-01-03',
      video: false,
      vote_average: 6.4,
      vote_count: 11,
    },
    {
      backdrop_path: '/hmZnqijPaaACjenDkrbWcCmcADI.jpg',
      id: 549509,
      title: 'The Brutalist',
      original_title: 'The Brutalist',
      overview:
        'Escaping post-war Europe, visionary architect László Tóth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.',
      poster_path: '/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 114.429,
      release_date: '2024-12-20',
      video: false,
      vote_average: 6.0,
      vote_count: 37,
    },
    {
      backdrop_path: '/2wqYNWasS3cxjAvoNfUTAZ58XGT.jpg',
      id: 1088514,
      title: 'The Room Next Door',
      original_title: 'La habitación de al lado',
      overview:
        'Ingrid and Martha were close friends in their youth, when they worked together at the same magazine. Ingrid went on to become an autofiction novelist while Martha became a war reporter, and they were separated by the circumstances of life. After years of being out of touch, they meet again in an extreme but strangely sweet situation.',
      poster_path: '/786Uu8eHfctp2TkII7ga1AnTBSs.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'es',
      genre_ids: [18],
      popularity: 269.087,
      release_date: '2024-10-07',
      video: false,
      vote_average: 7.0,
      vote_count: 262,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
